# Generated by Django 3.1.4 on 2020-12-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201209_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150)),
                ('prosent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=150)),
                ('skills', models.ManyToManyField(to='portfolio.Skill')),
            ],
        ),
    ]
