# Generated by Django 3.1.4 on 2020-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_skill_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='photos/portfolio/%Y/%m/%d')),
                ('thumb', models.ImageField(upload_to='photos/portfolio/%Y/%m/%d')),
            ],
        ),
    ]
